import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * PXF docs sidebar.
 *
 * This sidebar is consumed by the second docs plugin instance (id: 'pxf')
 * which reads directly from the `pxf/docs` submodule.
 */
const sidebarsPxf: SidebarsConfig = {
  pxfSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebarsPxf;
